global:  
  scrape_interval: 15s
scrape_configs:
  - job_name: 'fastapi-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8000'] # Adjust the target if your app is running on a different host/port